<a href="https://colab.research.google.com/github/momodoofuzz007/Unit-13-Homework-Asn/blob/main/MJ_Code_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [ ]:
# Imports
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [ ]:
# Import applicants_data.csv to Google Colab
from google.colab import files
uploaded = files.upload()

Saving applicants_data.csv to applicants_data.csv

In [ ]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv("applicants_data.csv")

# Review the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [ ]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df1 = applicant_data_df.drop(columns = ["EIN","NAME"])

# Review the DataFrame
display(applicant_data_df1.head(3),applicant_data_df1.tail(3))

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [ ]:
# Create a list of categorical variables 
categorical_variables = ['APPLICATION_TYPE','AFFILIATION','CLASSIFICATION','USE_CASE','ORGANIZATION','INCOME_AMT','SPECIAL_CONSIDERATIONS']

# Display the categorical variables list
list(applicant_data_df1.dtypes[applicant_data_df1.dtypes == "object"].index)

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [ ]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse = False)

In [ ]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df1[categorical_variables])

/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [ ]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names_out(categorical_variables)
)

# Review the DataFrame
display(encoded_df.head(3),encoded_df.tail(3))

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [ ]:
# Dropping categorical variables from original df
numerical_variables = applicant_data_df1.drop(columns = categorical_variables)

# Review the DataFrame
numerical_variables.head()

   STATUS  ASK_AMT  IS_SUCCESSFUL
0       1     5000              1
1       1   108590              1
2       1     5000              0
3       1     6692              1
4       1   142590              1

In [ ]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat(
[
    numerical_variables,
    encoded_df
],
    axis = 1
)

# Review the DataFrame
display(encoded_df.head(3),encoded_df.tail(3))

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
34296,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [ ]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df["IS_SUCCESSFUL"]

# Display a sample of y
display(y[:5])

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [ ]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=["IS_SUCCESSFUL"])

# Review the features DataFrame
X.head(5)

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [ ]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [ ]:
# Create a StandardScaler instance
scaler = StandardScaler()

#Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [ ]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [ ]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  (number_input_features + 1) // 2

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [ ]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (hidden_nodes_layer1 + 1) // 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [ ]:
# Create the Sequential model instance
nn = Sequential()

In [ ]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [ ]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [ ]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=number_output_neurons, activation="relu"))

In [ ]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 58)                6786

 dense_1 (Dense)             (None, 29)                1711

 dense_2 (Dense)             (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [ ]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Fit the model using 50 epochs and the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 4s 2ms/step - loss: 1.6676 - accuracy: 0.6752
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.9274 - accuracy: 0.6995
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.8039 - accuracy: 0.7200
Epoch 4/50
804/804 [==============================] - 2s 3ms/step - loss: 0.8203 - accuracy: 0.7210
Epoch 5/50
804/804 [==============================] - 2s 3ms/step - loss: 0.8919 - accuracy: 0.7133
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.9149 - accuracy: 0.7042
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.8631 - accuracy: 0.7137
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.8959 - accuracy: 0.6900
Epoch 9/50
804/804 [==============================] - 3s 4ms/step - loss: 0.8714 - accuracy: 0.7142
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7957 - accuracy: 0.7193
Epoch 11/50
804/804 [==============================] - 3s 4ms/step - loss: 0.7339 - accuracy: 0.7234
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7654 - accuracy: 0.7205
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7095 - accuracy: 0.7236
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7036 - accuracy: 0.7215
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6930 - accuracy: 0.7284
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6879 - accuracy: 0.7240
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7128 - accuracy: 0.7247
Epoch 18/50
804/804 [==============================] - 3s 3ms/step - loss: 0.6839 - accuracy: 0.7302
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6795 - accuracy: 0.7293
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6822 - accuracy: 0.7287
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6521 - accuracy: 0.7305
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6389 - accuracy: 0.7332
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6335 - accuracy: 0.7317
Epoch 24/50
804/804 [==============================] - 2s 3ms/step - loss: 0.6308 - accuracy: 0.7322
Epoch 25/50
804/804 [==============================] - 3s 3ms/step - loss: 0.6213 - accuracy: 0.7344
Epoch 26/50
804/804 [==============================] - 2s 3ms/step - loss: 0.6304 - accuracy: 0.7309
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6447 - accuracy: 0.7269
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6100 - accuracy: 0.7335
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6088 - accuracy: 0.7346
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6061 - accuracy: 0.7339
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5961 - accuracy: 0.7327
Epoch 32/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5800 - accuracy: 0.7353
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5851 - accuracy: 0.7357
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5774 - accuracy: 0.7357
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5884 - accuracy: 0.7360
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5990 - accuracy: 0.7305
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5957 - accuracy: 0.7287
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5899 - accuracy: 0.7339
Epoch 39/50
804/804 [==============================] - 3s 3ms/step - loss: 0.6134 - accuracy: 0.7246
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5922 - accuracy: 0.7295
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5899 - accuracy: 0.7337
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5830 - accuracy: 0.7358
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5862 - accuracy: 0.7371
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5836 - accuracy: 0.7361
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5809 - accuracy: 0.7347
Epoch 46/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5895 - accuracy: 0.7333
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5873 - accuracy: 0.7365
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5894 - accuracy: 0.7368
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5944 - accuracy: 0.7337
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5881 - accuracy: 0.7356

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [ ]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [ ]:
# Set the model's file path
file_path = "/Users/mohjaiswal/Desktop/Unit-13-Homework-Asn/Resources/AlphabetSoup.h5"

# Export your model to a HDF5 file
nn.save(file_path)

# Download your model to your computer
files.download(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [ ]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [ ]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 87

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

87

In [ ]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [ ]:

# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu"))

# Output layer
nn_A1.add(Dense(units=number_output_neurons_A1, activation="sigmoid")) 

# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 87)                10179

 dense_4 (Dense)             (None, 1)                 88

=================================================================
Total params: 10,267
Trainable params: 10,267
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 3s 2ms/step - loss: 0.5808 - accuracy: 0.7188
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5579 - accuracy: 0.7278
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5553 - accuracy: 0.7297
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5527 - accuracy: 0.7306
Epoch 5/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5522 - accuracy: 0.7303
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7314
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7308
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5482 - accuracy: 0.7327
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7312
Epoch 10/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5465 - accuracy: 0.7326
Epoch 11/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5461 - accuracy: 0.7320
Epoch 12/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5460 - accuracy: 0.7337
Epoch 13/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5454 - accuracy: 0.7346
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7341
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5439 - accuracy: 0.7341
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5440 - accuracy: 0.7343
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7348
Epoch 18/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5435 - accuracy: 0.7346
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7342
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7350
Epoch 21/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5425 - accuracy: 0.7340
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7355
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7346
Epoch 24/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5420 - accuracy: 0.7361
Epoch 25/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5414 - accuracy: 0.7354
Epoch 26/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5412 - accuracy: 0.7355
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7349
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7343
Epoch 29/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5402 - accuracy: 0.7358
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7358
Epoch 31/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5392 - accuracy: 0.7352
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7364
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7347
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7360
Epoch 35/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5397 - accuracy: 0.7370
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7340
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7365
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7351
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7367
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7362
Epoch 41/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5389 - accuracy: 0.7364
Epoch 42/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5383 - accuracy: 0.7364
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7352
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7373
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7378
Epoch 46/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5385 - accuracy: 0.7372
Epoch 47/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5379 - accuracy: 0.7371
Epoch 48/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5396 - accuracy: 0.7353
Epoch 49/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5375 - accuracy: 0.7376
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7374

#### Alternative Model 2

In [ ]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [ ]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 96

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

96

In [ ]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A2 = 66

# Review the number of hidden nodes in the second layer
hidden_nodes_layer2_A2

66

In [ ]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [ ]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer2_A2, activation="relu"))

# Output layer
nn_A2.add(Dense(units=number_output_neurons_A2, activation="sigmoid")) 

# Check the structure of the model
nn_A2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_5 (Dense)             (None, 96)                11232

 dense_6 (Dense)             (None, 66)                6402

 dense_7 (Dense)             (None, 1)                 67

=================================================================
Total params: 17,701
Trainable params: 17,701
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer= "adam", metrics=['accuracy'])

In [ ]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5732 - accuracy: 0.7224
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5533 - accuracy: 0.7295
Epoch 3/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5502 - accuracy: 0.7308
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5472 - accuracy: 0.7329
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7320
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5450 - accuracy: 0.7338
Epoch 7/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5439 - accuracy: 0.7329
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7356
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7353
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7362
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7368
Epoch 12/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7349
Epoch 13/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5401 - accuracy: 0.7372
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7374
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7370
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7357
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7371
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7394
Epoch 19/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5379 - accuracy: 0.7394
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7390
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7381
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7396
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7385
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7385
Epoch 25/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5356 - accuracy: 0.7396
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5356 - accuracy: 0.7390
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7395
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5349 - accuracy: 0.7388
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7390
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7396
Epoch 31/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5346 - accuracy: 0.7390
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5342 - accuracy: 0.7399
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7396
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7406
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7411
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5332 - accuracy: 0.7406
Epoch 37/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5331 - accuracy: 0.7406
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5328 - accuracy: 0.7415
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5329 - accuracy: 0.7411
Epoch 40/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5323 - accuracy: 0.7401
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5330 - accuracy: 0.7405
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5319 - accuracy: 0.7414
Epoch 43/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5326 - accuracy: 0.7412
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7411
Epoch 45/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5318 - accuracy: 0.7410
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5319 - accuracy: 0.7411
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5316 - accuracy: 0.7419
Epoch 48/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5314 - accuracy: 0.7416
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5315 - accuracy: 0.7415
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5313 - accuracy: 0.7414
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5315 - accuracy: 0.7402
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5311 - accuracy: 0.7420
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5308 - accuracy: 0.7418
Epoch 54/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5308 - accuracy: 0.7421
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5309 - accuracy: 0.7423
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5301 - accuracy: 0.7415
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5300 - accuracy: 0.7421
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7421
Epoch 59/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5301 - accuracy: 0.7426
Epoch 60/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5303 - accuracy: 0.7414
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7423
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7426
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7421
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5300 - accuracy: 0.7421
Epoch 65/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5298 - accuracy: 0.7411
Epoch 66/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5295 - accuracy: 0.7418
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5289 - accuracy: 0.7421
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7422
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5292 - accuracy: 0.7419
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5289 - accuracy: 0.7421
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5287 - accuracy: 0.7429
Epoch 72/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5288 - accuracy: 0.7423
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7421
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5283 - accuracy: 0.7415
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7418
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5281 - accuracy: 0.7414
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5291 - accuracy: 0.7423
Epoch 78/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5281 - accuracy: 0.7422
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7421
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5289 - accuracy: 0.7427
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5284 - accuracy: 0.7426
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5282 - accuracy: 0.7431
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5284 - accuracy: 0.7425
Epoch 84/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5278 - accuracy: 0.7435
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5280 - accuracy: 0.7423
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7425
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7422
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5280 - accuracy: 0.7425
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5280 - accuracy: 0.7428
Epoch 90/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5278 - accuracy: 0.7428
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5281 - accuracy: 0.7430
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5276 - accuracy: 0.7430
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5278 - accuracy: 0.7436
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5272 - accuracy: 0.7434
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5272 - accuracy: 0.7432
Epoch 96/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5277 - accuracy: 0.7425
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5278 - accuracy: 0.7428
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5280 - accuracy: 0.7425
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5269 - accuracy: 0.7431
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5277 - accuracy: 0.7423

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [ ]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 1s - loss: 0.6103 - accuracy: 0.7265 - 635ms/epoch - 2ms/step
Loss: 0.6102955341339111, Accuracy: 0.7265306115150452

In [ ]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 1s - loss: 0.5652 - accuracy: 0.7298 - 559ms/epoch - 2ms/step
Loss: 0.565214991569519, Accuracy: 0.7297959327697754

In [ ]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 1s - loss: 0.5751 - accuracy: 0.7291 - 897ms/epoch - 3ms/step
Loss: 0.5751439929008484, Accuracy: 0.7290962338447571

### Step 3: Save each of your alternative models as an HDF5 file.

In [ ]:
# Set the file path for the first alternative model
file_path = "/Users/mohjaiswal/Desktop/Unit-13-Homework-Asn/Resources/AlphabetSoup_A1.h5"

# Export your model to a HDF5 file
nn_A1.save(file_path)

# Download the model to your computer
files.download(file_path)

In [ ]:
# Set the file path for the second alternative model
file_path = "/Users/mohjaiswal/Desktop/Unit-13-Homework-Asn/Resources/AlphabetSoup_A2.h5"

# Export your model to a HDF5 file
nn_A2.save(file_path)

# Download the model to your computer
files.download(file_path)